### ISSUE TITLE
How to delete 1gb partition with VitaDeploy ?

### ISSUE THREAD

**Issue by ReadyKim** [SKGleba/VitaDeploy#41]
I created internal memory card (1Gb) on PSP Vita 1000.  (firmware now 3.65 with reset)
I want  back to stock memory.  

I think i need install Henkaku,  install VitaDeploy with replace app Near.
What i need do then?

**Comment by SKGleba** [comment]
VitaDeploy's create an internal memory card option.
It will launch imcunlock, you can remove the 1gb from there ("Default 1XXX..." option).
Keep in mind that to avoid a memory card slot softbrick, if you dont have a memory card inserted it will reduce the partition size to 0MB instead of removing it.

**Comment by ReadyKim** [comment]
Does Memory card Sony  will format?

**Comment by SKGleba** [comment]
no

**Comment by ReadyKim** [comment]
Thx. i back to stock
Do you know how  to unlink from account memory card Sony? 

My account PSN hacked. Sticker with serial number lost. I can't revover account.

**Comment by ReadyKim** [comment]
I check hack PSP Vita 1000 with create 1Gb imc. And in settings VitaDeploy choose unlink memory card, but its unlink 1Gb imc. 

Now i back to stock.

**Comment by ReadyKim** [comment]
i need copy files from memory card Sony, but i cant unlock
